export * from './contestant.model';
export * from './contestant-popup.service';
export * from './contestant.service';
export * from './contestant-dialog.component';
export * from './contestant-delete-dialog.component';
export * from './contestant-detail.component';
export * from './contestant.component';
export * from './contestant.route';
export * from './register/contestant-register-dialog.component';
